// scripts/ob_crypt.shader
//
// The three OpenArena shader definitions maps/ob_crypt.bsp references that are
// not plain images, copied verbatim (GPLv2, OpenArena -- see NOTICE) out of
// oa-pak0.pk3's scripts/oalite.shader and scripts/liquid_lavas.shader.
//
// Copied rather than bundling those files whole because every mounted pak's
// shader scripts apply to every course by NAME: shipping all of oalite.shader
// would attach ~200 shader definitions, most with images this pak does not
// carry, to any other map that happens to use the same texture names. A few
// definitions with every stage image bundled is the whole footprint.
//
// GENERATED by tools/extract-oa-shaders.ts (`npm run extract-oa-shaders`).
// Do not hand-edit; change COURSES there and rerun.

textures/gothic_light/ironcrosslt2_5000
{
	qer_editorimage textures/gothic_light/ironcrosslt2_10000.tga
	q3map_lightimage textures/gothic_light/ironcrosslt2_5000_blend.tga
	q3map_surfacelight 5000
	q3map_flare flareShader
	{
		map textures/gothic_light/ironcrosslt2_5000.tga
		rgbGen identity
	}
	{
		map $lightmap 
		blendfunc filter
		tcGen lightmap 
	}
	{
		map textures/gothic_light/ironcrosslt2_5000_blend.tga
		blendfunc add
		rgbGen wave noise 0.8 0.2 0 1 
	}
}

textures/gothic_light/pentagram_light1_3k
{
	qer_editorimage textures/gothic_light/pentagram_light1_3k.tga
	q3map_lightimage textures/gothic_light/pentagram_light1_3k_blend.tga
	surfaceparm nomarks
	q3map_surfacelight 3000
	q3map_flare flareShader
	{
		map textures/gothic_light/pentagram_light1_3k.tga
		rgbGen identity
	}
	{
		map $lightmap 
		blendfunc filter
		tcGen lightmap 
	}
	{
		map textures/gothic_light/pentagram_light1_3k_blend.tga
		blendfunc add
		rgbGen wave noise 0.8 0.2 0 1 
	}
}

textures/liquids/lavahell_simple
{
	q3map_lightimage textures/liquids/lavahell.tga
	qer_editorimage textures/liquids/lavahell
	surfaceparm lava
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm water
	surfaceparm lightfilter
	cull disable
	q3map_surfacelight 666
	q3map_globaltexture
	q3map_flare textures/flares/lava
	{
		map textures/liquids/lavahell.tga
		tcMod turb 1 -0.3 0 0.07
	}
}
