// scripts/ob_circuit.shader
//
// The OpenArena shader definitions maps/ob_circuit.bsp references that are
// not plain images -- the scrolling blue and red light trims that colour-code
// the high and low lanes, the blue tiny light and the amber panel of the mid
// lane, and the evil8 jump pad on each hub floor (round 2) -- copied verbatim
// (GPLv2, OpenArena -- see NOTICE) out of oa-pak0.pk3's scripts/evil8.shader
// and scripts/cosmoflash.shader. The sky (skies/earthsky01) comes from
// oasky.shader, which the pak carries whole.
//
// Copied rather than bundling those files whole because every mounted pak's
// shader scripts apply to every course by NAME: shipping all of oalite.shader
// would attach ~200 shader definitions, most with images this pak does not
// carry, to any other map that happens to use the same texture names. A few
// definitions with every stage image bundled is the whole footprint.
//
// GENERATED by tools/extract-oa-shaders.ts (`npm run extract-oa-shaders`).
// Do not hand-edit; change COURSES there and rerun.

textures/evil8_trim/e8trimlight2_blue
{
	qer_editorimage textures/evil8_trim/e8trimlight2_blue.tga
	surfaceparm nomarks
	q3map_surfacelight 400
	q3map_flare flareShader
	{
		map textures/evil8_trim/e8trimlight2_blue.tga
	}
	{
		map $lightmap 
		blendfunc filter
		tcGen lightmap 
	}
	{
		map textures/evil8_trim/e8trimlight2_blue.blend.tga
		blendfunc add
		tcMod scroll -0.7 0
	}
}

textures/evil8_trim/e8trimlight2_red
{
	qer_editorimage textures/evil8_trim/e8trimlight2_red.tga
	surfaceparm nomarks
	q3map_surfacelight 400
	q3map_flare flareShader
	{
		map textures/evil8_trim/e8trimlight2_red.tga
	}
	{
		map $lightmap 
		blendfunc filter
		tcGen lightmap 
	}
	{
		map textures/evil8_trim/e8trimlight2_red.blend.tga
		blendfunc add
		tcMod scroll -0.7 0
	}
}

textures/evil8_lights/e8tinylightblue
{
	qer_editorimage textures/evil8_lights/e8tinylightblue.tga
	surfaceparm nomarks
	q3map_surfacelight 950
	q3map_flare flareShader
	{
		map textures/evil8_lights/e8tinylightblue.tga
	}
	{
		map $lightmap 
		blendfunc filter
		tcGen lightmap 
	}
	{
		map textures/evil8_lights/e8tinylightblue.blend.tga
		blendfunc add
	}
}

textures/bubctf1/e8_jumppad02
{
	q3map_lightimage textures/bubctf1/e8_jumppad02_fx.tga
	surfaceparm nodamage
	polygonoffset
	q3map_surfacelight 200
	{
		map textures/bubctf1/e8_jumppad02.tga
		rgbGen identity
	}
	{
		map textures/bubctf1/e8_jumppad02_fx.tga
		blendfunc add
		tcMod rotate 360
		tcMod stretch sin 1 0.8 1 0.4 
	}
	{
		map textures/bubctf1/e8_jumppad02.tga
		blendfunc blend
		rgbGen identity
	}
	{
		map $lightmap 
		blendfunc gl_dst_color gl_one_minus_dst_alpha
		rgbGen identity
		tcGen lightmap 
	}
}

textures/cosmo_light/lightyel02_12k
{
	qer_editorimage textures/cosmo_light/lightyel02.jpg
	surfaceparm nomarks
	q3map_surfacelight 12000
	{
		map textures/cosmo_light/lightyel02.jpg
		rgbgen identity
	}
	{
		map $lightmap
        blendFunc filter
		tcgen lightmap
	}
}
