// scripts/ob_grounds.shader
//
// The OpenArena shader definitions maps/ob_grounds.bsp references that are
// not plain images -- the pale grey mist of the fog garden, the gothic wall lamps and
// the torch flames -- copied verbatim (GPLv2, OpenArena -- see NOTICE) out of
// oa-pak0.pk3's scripts/oa_fogs.shader, scripts/oalite.shader and
// scripts/oasfx.shader. The sky (skies/moonsky) comes from
// oasky.shader, which the pak carries whole.
//
// Copied rather than bundling those files whole because every mounted pak's
// shader scripts apply to every course by NAME: shipping all of oalite.shader
// would attach ~200 shader definitions, most with images this pak does not
// carry, to any other map that happens to use the same texture names. A few
// definitions with every stage image bundled is the whole footprint.
//
// GENERATED by tools/extract-oa-shaders.ts (`npm run extract-oa-shaders`).
// Do not hand-edit; change COURSES there and rerun.

textures/sfx/xnotsodensegreyfog
{
        surfaceparm trans
        surfaceparm nonsolid
	surfaceparm fog
	surfaceparm nomarks
        cull disable
        fogparms ( 0.4784 0.4784 0.4784 ) 600
	{
		map textures/liquids/kc_fogcloud3.tga
		blendfunc filter
		tcMod turb .01 .5 0 .05
	}
	{
		map textures/liquids/kc_fogcloud3.tga
		blendfunc filter
		tcMod scroll -.02 .02
	}
}

textures/gothic_light/gothic_light3_2K
{
	qer_editorimage textures/gothic_light/gothic_light3.jpg
	q3map_lightimage textures/gothic_light/gothic_light2_blend.jpg
	q3map_surfacelight 2000
	surfaceparm nomarks
	q3map_flare flareShader
	{
		map $lightmap
		rgbgen identity
	}
	{
		map textures/gothic_light/gothic_light3.jpg
		rgbgen identity
		blendfunc filter
	}
	{
		map textures/gothic_light/gothic_light2_blend.jpg
		blendfunc add
		rgbgen wave sin .4 .4 0 .1
	}
}

textures/sfx/flame1side
{
	qer_editorimage textures/sfx/flame6.tga
	surfaceparm nolightmap
	surfaceparm nomarks
	cull disable
	deformVertexes wave 194 sin 0 1 0 .6
	{
		animmap 10 textures/sfx/flame1.tga textures/sfx/flame2.tga textures/sfx/flame3.tga textures/sfx/flame4.tga textures/sfx/flame5.tga textures/sfx/flame6.tga textures/sfx/flame7.tga textures/sfx/flame8.tga 
		blendfunc gl_src_alpha gl_one
		alphaGen wave inversesawtooth 0 1 0 10 
	}
	{
		animmap 10 textures/sfx/flame2.tga textures/sfx/flame3.tga textures/sfx/flame4.tga textures/sfx/flame5.tga textures/sfx/flame6.tga textures/sfx/flame7.tga textures/sfx/flame8.tga textures/sfx/flame1.tga
		blendfunc gl_src_alpha gl_one
		alphaGen wave sawtooth 0 1 0 10 
	}
}
