// scripts/ob_strafes.shader
//
// The OpenArena shader definitions maps/ob_strafes.bsp references that are
// not plain images -- the iron-cross and pentagram lamps and the torch flames --
// copied verbatim (GPLv2, OpenArena -- see NOTICE) out of oa-pak0.pk3's
// scripts/oalite.shader and scripts/oasfx.shader. The sky (skies/nitesky)
// comes from oasky.shader, which the pak carries whole.
//
// Copied rather than bundling those files whole because every mounted pak's
// shader scripts apply to every course by NAME: shipping all of oalite.shader
// would attach ~200 shader definitions, most with images this pak does not
// carry, to any other map that happens to use the same texture names. A few
// definitions with every stage image bundled is the whole footprint.
//
// GENERATED by tools/extract-oa-shaders.ts (`npm run extract-oa-shaders`).
// Do not hand-edit; change COURSES there and rerun.

textures/gothic_light/ironcrosslt2_5000
{
	qer_editorimage textures/gothic_light/ironcrosslt2_10000.tga
	q3map_lightimage textures/gothic_light/ironcrosslt2_5000_blend.tga
	q3map_surfacelight 5000
	q3map_flare flareShader
	{
		map textures/gothic_light/ironcrosslt2_5000.tga
		rgbGen identity
	}
	{
		map $lightmap 
		blendfunc filter
		tcGen lightmap 
	}
	{
		map textures/gothic_light/ironcrosslt2_5000_blend.tga
		blendfunc add
		rgbGen wave noise 0.8 0.2 0 1 
	}
}

textures/gothic_light/pentagram_light1_3k
{
	qer_editorimage textures/gothic_light/pentagram_light1_3k.tga
	q3map_lightimage textures/gothic_light/pentagram_light1_3k_blend.tga
	surfaceparm nomarks
	q3map_surfacelight 3000
	q3map_flare flareShader
	{
		map textures/gothic_light/pentagram_light1_3k.tga
		rgbGen identity
	}
	{
		map $lightmap 
		blendfunc filter
		tcGen lightmap 
	}
	{
		map textures/gothic_light/pentagram_light1_3k_blend.tga
		blendfunc add
		rgbGen wave noise 0.8 0.2 0 1 
	}
}

textures/sfx/flame1side
{
	qer_editorimage textures/sfx/flame6.tga
	surfaceparm nolightmap
	surfaceparm nomarks
	cull disable
	deformVertexes wave 194 sin 0 1 0 .6
	{
		animmap 10 textures/sfx/flame1.tga textures/sfx/flame2.tga textures/sfx/flame3.tga textures/sfx/flame4.tga textures/sfx/flame5.tga textures/sfx/flame6.tga textures/sfx/flame7.tga textures/sfx/flame8.tga 
		blendfunc gl_src_alpha gl_one
		alphaGen wave inversesawtooth 0 1 0 10 
	}
	{
		animmap 10 textures/sfx/flame2.tga textures/sfx/flame3.tga textures/sfx/flame4.tga textures/sfx/flame5.tga textures/sfx/flame6.tga textures/sfx/flame7.tga textures/sfx/flame8.tga textures/sfx/flame1.tga
		blendfunc gl_src_alpha gl_one
		alphaGen wave sawtooth 0 1 0 10 
	}
}
