// scripts/ob_yard.shader
//
// The two OpenArena shader definitions maps/ob_yard.bsp references that are
// not plain images -- the pulsing jump pad and the blue running lights --
// copied verbatim (GPLv2, OpenArena -- see NOTICE) out of oa-pak0.pk3's
// scripts/oasfx.shader and scripts/oalite.shader. The sky (skies2/nebula3)
// comes from oasky.shader, which the pak carries whole.
//
// Copied rather than bundling those files whole because every mounted pak's
// shader scripts apply to every course by NAME: shipping all of oalite.shader
// would attach ~200 shader definitions, most with images this pak does not
// carry, to any other map that happens to use the same texture names. A few
// definitions with every stage image bundled is the whole footprint.
//
// GENERATED by tools/extract-oa-shaders.ts (`npm run extract-oa-shaders`).
// Do not hand-edit; change COURSES there and rerun.

textures/sfx/diamond2cjumppad
{
	qer_editorimage textures/sfx/bouncepad01_diamond2cTGA.jpg
	q3map_lightimage textures/clown/circ4glow.tga
	q3map_surfacelight 100
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/sfx/bouncepad01_diamond2cTGA.jpg
		blendFunc filter
		rgbGen identity
	}
	{
		map textures/clown/circ4glow.tga
		blendFunc add
		rgbGen wave sin 0.2 0.2 0 .9
	}
}

textures/base_light/proto_lightblue
{
	qer_editorimage textures/base_light/proto_lightblue.jpg
	surfaceparm nomarks
	q3map_surfacelight 1500
	{
	
		map $lightmap
		rgbGen identity
	}
	{	
		map textures/base_light/proto_lightblue.jpg
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/base_light/proto_lightblue.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen wave square  1 1 .5 1
	}
}
