/**
 * Regenerate `scripts/ob_crypt.shader` from OpenArena's own shader scripts.
 *
 * Copyright (C) 2026 Overbounce contributors
 * Licensed under the GNU General Public License v2 or later. See LICENSE.
 *
 *   npm run download-assets       # oa-pak0.pk3 is where the scripts live
 *   npm run extract-oa-shaders
 *
 * A mounted pak's shader scripts apply to every course by NAME, so a course
 * that needs three OpenArena shader definitions ships exactly those three,
 * with every stage image bundled, instead of the whole `oalite.shader` and
 * `liquid_lavas.shader` (hundreds of definitions whose images this project
 * does not carry, attached to any other map that shares a texture name).
 *
 * Each block is copied verbatim -- the file is GPLv2 OpenArena text, see
 * NOTICE -- by matching the `textures/...` header line and brace-counting to
 * the end of its definition. Edit `BLOCKS` to change what ob_crypt needs; do
 * not hand-edit the output.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { openAsBlob } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Pk3FileSystem } from '../src/assets/pk3.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OA_PAK = 'assets/pk3/oa-pak0.pk3';
const OUT = 'scripts/ob_crypt.shader';

/** OpenArena script -> shader definitions ob_crypt references from it. */
const BLOCKS: readonly { script: string; names: readonly string[] }[] = [
  {
    script: 'scripts/oalite.shader',
    names: ['textures/gothic_light/ironcrosslt2_5000', 'textures/gothic_light/pentagram_light1_3k'],
  },
  { script: 'scripts/liquid_lavas.shader', names: ['textures/liquids/lavahell_simple'] },
];

const HEADER = `// scripts/ob_crypt.shader
//
// The three OpenArena shader definitions maps/ob_crypt.bsp references that are
// not plain images, copied verbatim (GPLv2, OpenArena -- see NOTICE) out of
// oa-pak0.pk3's scripts/oalite.shader and scripts/liquid_lavas.shader.
//
// Copied rather than bundling those files whole because every mounted pak's
// shader scripts apply to every course by NAME: shipping all of oalite.shader
// would attach ~200 shader definitions, most with images this pak does not
// carry, to any other map that happens to use the same texture names. Three
// definitions with every stage image bundled is the whole footprint.
//
// GENERATED by tools/extract-oa-shaders.ts (\`npm run extract-oa-shaders\`).
// Do not hand-edit; change BLOCKS there and rerun.

`;

/** The definition starting at the line that is exactly `name`, through its closing brace. */
function extractBlock(text: string, name: string, script: string): string {
  const lines = text.split(/\r?\n/);
  const start = lines.findIndex((l) => l.trim() === name);
  if (start < 0) {
    throw new Error(`${name} is not defined in ${script}`);
  }
  const out: string[] = [];
  let depth = 0;
  let opened = false;
  for (let i = start; i < lines.length; i++) {
    const line = lines[i]!;
    out.push(line);
    for (const ch of line) {
      if (ch === '{') {
        depth++;
        opened = true;
      } else if (ch === '}') {
        depth--;
      }
    }
    if (opened && depth === 0) {
      return out.join('\n');
    }
  }
  throw new Error(`${name} in ${script} never closes`);
}

async function main(): Promise<void> {
  const oaPak = new Pk3FileSystem();
  await oaPak.mount('oa-pak0.pk3', await openAsBlob(join(root, OA_PAK)));

  const blocks: string[] = [];
  for (const { script, names } of BLOCKS) {
    const bytes = await oaPak.readFile(script);
    if (!bytes) {
      throw new Error(`${script} is not in ${OA_PAK}`);
    }
    const text = new TextDecoder().decode(bytes);
    for (const name of names) {
      blocks.push(extractBlock(text, name, script));
    }
  }

  const output = HEADER + blocks.join('\n\n') + '\n';
  const target = join(root, OUT);
  let previous = '';
  try {
    previous = readFileSync(target, 'utf8');
  } catch {
    // first run
  }
  writeFileSync(target, output);
  console.log(`${OUT}: ${blocks.length} definitions${previous === output ? ' (unchanged)' : ''}`);
}

await main();
