"""Generate src/demo/netfields.ts from refs/quake3/qcommon/msg.c.

The netfield tables are the wire format for `.dm_68`: their ORDER is the
protocol, and a single transposed line silently decodes a demo into plausible
nonsense. Transcribing 99 entries by hand is exactly the kind of thing
CLAUDE.md's "every fidelity bug found in this project so far was found by
diffing against that C" warns about, so they are extracted mechanically
instead. Re-run after a `npm run download-assets -- --refs`:

    python tools/gen-netfields.py

The generated file is committed; this script is how it is reproduced, not a
build step.
"""

import io
import os
import re

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, 'refs', 'quake3', 'qcommon', 'msg.c')
OUT = os.path.join(HERE, 'src', 'demo', 'netfields.ts')

BITS = {'GENTITYNUM_BITS': '10'}


def table(text, marker):
    i = text.index(marker)
    j = text.index('};', i)
    body = text[i:j]
    out = []
    for m in re.finditer(r'\{\s*(?:NETF|PSF)\(([^)]*)\)\s*,\s*(-?\w+)\s*\}', body):
        name, bits = m.group(1), m.group(2)
        out.append((name, BITS.get(bits, bits)))
    return out


def slot_name(name):
    """`pos.trBase[0]` -> `pos_trBase_0`, a legal TS identifier."""
    return name.replace('.', '_').replace('[', '_').replace(']', '')


def emit(entries, kind, start):
    lines = []
    for i, (name, bits) in enumerate(entries):
        lines.append(
            "  { name: '%s', slot: %d, bits: %s },"
            % (name, start + i, bits)
        )
    return '\n'.join(lines)


def emit_slots(entries, extra, indent='  '):
    lines = []
    slot = 0
    for name in extra:
        lines.append('%s%s: %d,' % (indent, name, slot))
        slot += 1
    for name, _bits in entries:
        lines.append('%s%s: %d,' % (indent, slot_name(name), slot))
        slot += 1
    return '\n'.join(lines)


def main():
    text = io.open(SRC, encoding='utf-8', errors='replace').read()
    ents = table(text, 'netField_t\tentityStateFields[]')
    pss = table(text, 'netField_t\tplayerStateFields[]')
    assert len(ents) == 51, len(ents)
    assert len(pss) == 48, len(pss)

    out = HEADER
    out += 'export const ENTITY_FIELDS: readonly NetField[] = [\n'
    out += emit(ents, 'entity', 1) + '\n];\n\n'
    out += (
        '/** Slot count for one `entityState_t`: `number` plus the %d net fields. */\n'
        'export const ENTITY_SLOTS = %d;\n\n' % (len(ents), len(ents) + 1)
    )
    out += (
        '/**\n'
        ' * Where each `entityState_t` member lives in the word array.\n'
        ' *\n'
        " * Slot 0 is `number`, which is NOT a net field -- it rides the packet\n"
        ' * entity header instead. The rest follow the net table order, which is an\n'
        ' * arbitrary but stable choice: only the name-to-slot mapping matters here,\n'
        ' * where in `ENTITY_FIELDS` the ORDER is the wire format itself.\n'
        ' */\n'
        'export const ES = {\n'
    )
    out += emit_slots(ents, ['number']) + '\n} as const;\n\n'

    out += 'export const PLAYER_FIELDS: readonly NetField[] = [\n'
    out += emit(pss, 'player', 0) + '\n];\n\n'
    out += (
        '/** Slot count for one `playerState_t`. The stats/persistant/ammo/powerups\n'
        ' *  arrays are NOT in here -- they are delta-coded separately. */\n'
        'export const PLAYER_SLOTS = %d;\n\n' % len(pss)
    )
    out += (
        '/** Where each `playerState_t` net member lives in the word array. */\n'
        'export const PS = {\n'
    )
    out += emit_slots(pss, []) + '\n} as const;\n'

    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(out)
    print('wrote %s (%d entity fields, %d playerstate fields)' % (OUT, len(ents), len(pss)))


HEADER = '''/**
 * The `.dm_68` netfield tables.
 * Ported from Quake III Arena's code/qcommon/msg.c.
 *
 * Copyright (C) 1999-2005 Id Software, Inc.
 * Copyright (C) 2026 Overbounce contributors
 * Licensed under the GNU General Public License v2 or later. See LICENSE.
 *
 * GENERATED by `tools/gen-netfields.py` from `refs/quake3/qcommon/msg.c`.
 * Do not edit by hand -- re-run the script.
 *
 * **The order of these tables IS the wire format.** A delta message says how
 * many fields changed (`lc`) and then writes exactly that many change bits in
 * this order; move one line and every demo decodes into plausible nonsense
 * with no error raised anywhere. That is why they are extracted mechanically
 * rather than transcribed, and why the generator asserts the counts (51 and
 * 48) it found.
 *
 * `bits: 0` does NOT mean "no bits". It means the field is a float, sent
 * either as zero, as a 13-bit biased integer when it happens to be integral,
 * or as a raw 32-bit pattern. `bits < 0` means a signed integer of that
 * width.
 */

/** One `netField_t`. `slot` is the index into the state's word array. */
export interface NetField {
  name: string;
  slot: number;
  bits: number;
}

'''

if __name__ == '__main__':
    main()
